<h1 id="ErrorHandling-ErrorHandlingStrategies">Error Handling Strategies</h1><p>There are a couple of basic strategies to handle errors and exceptions within processes. The decision which strategy to use depends on:</p><ul><li>Technical vs. Business Errors: Does the error have some business meaning and causes an alternative process flow (like item not on stock) or is it some technical malfunction (like network currently down)?</li><li>Explicit error handling or generic approach: For some situations you want to explicitly model what should happen in case of an error (typcially for business errors). For a lot of situations you don't want to do that but have some generic mechanism which applies for errors, simplyfying your process models (typical for technical errors, imagine you would have to model network outtage on every task were it might possibly occur? You woldn't recognize your business process any more).</li></ul><p>In the context of the fox engine, errors are normally raised as Java excepions you have to handle. Let's have a look on how to handle them.</p><h2 id="ErrorHandling-TransactionRollbacks">Transaction Rollbacks</h2><p>The standard handling strategy in the fox engine is that exceptions are thrown to the client, meaning the current transaction is rolled back. This means the process state is rolled back to the last wait state. This behavior is described in detail in <a href="/confluence/display/foxUserGuide/Thread+and+Transaction+Management">Thread and Transaction Management</a>. The error handling is delegated to the client of the engine, which is at least easy, but often not desired.</p><p>As a concrete example this would mean, that the user gets an error dialog on the fronted, that the stock management software is currently not reachable due to network errors. To retry the user might have to click the same button again. Even if this is often not desired it is still a simple strategy applicable in a lot of situations.</p><h2 id="ErrorHandling-FailedJobs">Failed Jobs</h2><p>If you don't want the exception being show to the user one option is to make service calls which might cause an error async as described in <a href="/confluence/display/foxUserGuide/Thread+and+Transaction+Management">Thread and Transaction Management</a>. In this case the exception is stored in the fox engine database and&nbsp;<a href="/confluence/display/foxUserGuide/The+Job+Executor">The Job Executor</a> in the background is marked as failed (to be more precise, the exception is stored and some retry counter is decremented).</p><p>'In the example above this means that the user will not see an error but an "everything successful" dialog. The exception is stored on the job. Now either a clever retry strategy will automatically re-trigger the job later on (when the network is available again) or some operator needs to have a look at the error and trigger an additional retry. This is shown later in more details.</p><p>This strategy is pretty powerful and applied often in real-life projects, however, it still hides the error from the BPMN diagram, so for business errors which you want to be visible in the process diagram, you better use error events as described below.</p><h2 id="ErrorHandling-CatchExceptionandusedatabasedXOR-Gateway">Catch Exception and use data based XOR-Gateway</h2><p>If you call Java Code which can throw an exception you can catch the exception within the Java Delegate, CDI Bean or whatsoever. Maybe it is already sufficient to log some information and go on, meaning to ignore the error. More often you write the result into some process variable and model an XOR-Gateway later in the process flow to take a different path if that error occurred.</p><p>In this case you model the error handling explicitly in the process model but let it look like a normal result and not like an error. From a business perspective it is not an error but a result, so the decision should not be made lightly. A rule of thumb is that results can be handled this way, exceptional errors should not. The BPMN perspective doesn't have to match the technical implementation. Example:</p><p><img class="confluence-embedded-image" src="/confluence/download/attachments/6062301/error-result-xor.png?version=1&amp;modificationDate=1340023452000" data-image-src="/confluence/download/attachments/6062301/error-result-xor.png?version=1&amp;modificationDate=1340023452000"></p><p>We trigger a "check data completeness" task. The Java Service might throw an "DataIncompleteException". However, if we check for completeness, incomplete data is not a exception, but an expected result, so we prefer using an XOR-Gateway in the process flow, evaluation a process variable, e.g. "<code>#{dataComplete==false}</code>".</p><h2 id="ErrorHandling-BPMN20ErrorEvent">BPMN 2.0 Error Event</h2><p>The BPMN 2.0 error event gives you a possibility to explicitly model errors, tackling the use case of business errors. There is a distinction between raising errors (throw events) and handling errors (catch events).</p><h3 id="ErrorHandling-CatchingErrors">Catching Errors</h3><p>The most prominent example is the "intermediate catching error event", which can be attached to the boundary of an activity. Defining a boundary error event makes most sense on an embedded subprocess, a call activity or a Service Task. An error will cause the alternative process flow to be triggered:<br><br><img class="confluence-embedded-image confluence-external-resource" src="http://www.activiti.org/userguide/images/bpmn.boundary.error.event.png" data-image-src="http://www.activiti.org/userguide/images/bpmn.boundary.error.event.png"><br><br>Note that errors are propagated to parent scopes upwards until a scope is found on which a boundary error event is defined that matches the error event definition. See&nbsp;<a href="/confluence/display/foxUserGuide/BPMN+2.0+Constructs">BPMN 2.0 Constructs</a> for more information. An error event definition references an error element. The following is an example of an error event, referencing an error declaration:<br><br></p><div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<div><div id="highlighter_306817" class="syntaxhighlighter nogutter  html"><div class="toolbar"><span><a href="#" class="toolbar_item command_help help">?</a></span></div><table border="0" cellpadding="0" cellspacing="0"><tbody><tr><td class="code"><div class="container" title="Hint: double-click to select code"><div class="line number1 index0 alt2"><code class="html plain">&lt;</code><code class="html keyword">error</code> <code class="html color1">id</code><code class="html plain">=</code><code class="html string">"notOnStock"</code> <code class="html color1">errorCode</code><code class="html plain">=</code><code class="html string">"NOT_ON_STOCK_ERROR"</code> <code class="html plain">/&gt;</code></div><div class="line number2 index1 alt1"><code class="html plain">&lt;</code><code class="html keyword">process</code><code class="html plain">&gt;</code></div><div class="line number3 index2 alt2"><code class="html spaces">&nbsp;&nbsp;</code><code class="html plain">...</code></div><div class="line number4 index3 alt1"><code class="html spaces">&nbsp;&nbsp;</code><code class="html plain">&lt;</code><code class="html keyword">serviceTask</code> <code class="html color1">id</code><code class="html plain">=</code><code class="html string">"bookOutFromStock"</code> <code class="html plain">.../&gt;</code></div><div class="line number5 index4 alt2"><code class="html spaces">&nbsp;&nbsp;</code><code class="html plain">&lt;</code><code class="html keyword">boundaryEvent</code> <code class="html color1">id</code><code class="html plain">=</code><code class="html string">"catchError"</code> <code class="html color1">attachedToRef</code><code class="html plain">=</code><code class="html string">"bookOutFromStock"</code><code class="html plain">&gt;</code></div><div class="line number6 index5 alt1"><code class="html spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="html plain">&lt;</code><code class="html keyword">errorEventDefinition</code> <code class="html color1">errorRef</code><code class="html plain">=</code><code class="html string">"notOnStock"</code><code class="html plain">/&gt;</code></div><div class="line number7 index6 alt2"><code class="html spaces">&nbsp;&nbsp;</code><code class="html plain">&lt;/</code><code class="html keyword">boundaryEvent</code><code class="html plain">&gt;</code></div></div></td></tr></tbody></table></div></div>
</div></div><p>You can handle errors not only with boundary events, but also by having an error sub process. This means that the normal flow iscompletely interrupted and the sub process is started:</p><p><img class="confluence-embedded-image confluence-external-resource" src="http://www.bpm-guide.de/wp-content/uploads/2012/02/activiti59_bpmn_event_subprocess.png" data-image-src="http://www.bpm-guide.de/wp-content/uploads/2012/02/activiti59_bpmn_event_subprocess.png" width="300"></p><p>Note that currently event sub processes are only supported as interrupting sub processes, see <a href="/confluence/display/foxUserGuide/BPMN+2.0+Coverage">BPMN 2.0 Coverage</a>.</p><h3 id="ErrorHandling-ThrowingErrorsfromJavaCode">Throwing Errors from Java Code</h3><p>In the above example the error event is attached to a Service Task. In order to get this to work the Service Task has to throw the corresponding error. This is done by using a provided Java exception class from within your Java code (e.g. in the JavaDelegate):</p><div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<div><div id="highlighter_758503" class="syntaxhighlighter nogutter  java"><div class="toolbar"><span><a href="#" class="toolbar_item command_help help">?</a></span></div><table border="0" cellpadding="0" cellspacing="0"><tbody><tr><td class="code"><div class="container" title="Hint: double-click to select code"><div class="line number1 index0 alt2"><code class="java keyword">public</code> <code class="java keyword">class</code> <code class="java plain">BookOutGoodsDelegate </code><code class="java keyword">implements</code> <code class="java plain">JavaDelegate {</code></div><div class="line number2 index1 alt1"><code class="java spaces">&nbsp;&nbsp;</code><code class="java keyword">public</code> <code class="java keyword">void</code> <code class="java plain">execute(DelegateExecution execution) </code><code class="java keyword">throws</code> <code class="java plain">Exception {</code></div><div class="line number3 index2 alt2"><code class="java spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="java keyword">try</code> <code class="java plain">{</code></div><div class="line number4 index3 alt1"><code class="java spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="java plain">...</code></div><div class="line number5 index4 alt2"><code class="java spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="java plain">} </code><code class="java keyword">catch</code> <code class="java plain">(NotOnStockException ex) {</code></div><div class="line number6 index5 alt1"><code class="java spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="java keyword">throw</code> <code class="java keyword">new</code> <code class="java plain">BpmnError(NOT_ON_STOCK_ERROR);</code></div><div class="line number7 index6 alt2"><code class="java spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="java plain">}</code></div><div class="line number8 index7 alt1"><code class="java spaces">&nbsp;&nbsp;</code><code class="java plain">} </code></div><div class="line number9 index8 alt2"><code class="java plain">}</code></div></div></td></tr></tbody></table></div></div>
</div></div><h3 id="ErrorHandling-ThrowingErrorsusingBPMN20">Throwing Errors using BPMN 2.0</h3><p>Another possibility to raise errors is to use throwing error end events, which ends the current path of execution and throws the error:</p><p><img class="confluence-embedded-image confluence-external-resource" src="http://www.activiti.org/userguide/images/bpmn.error.end.event.png" data-image-src="http://www.activiti.org/userguide/images/bpmn.error.end.event.png"></p><h2 id="ErrorHandling-BusinessTransactions">Business Transactions</h2><p>The most sophisticated and little used concept are BPMN 2.0 business transactions and compensations. They allow you to model transaction boundaries, but not in a technical ACID manner, and make sure already executed actions are compensated during rollback. Compensation means, to make the effect of the action invisible, e.g. book in goods if you have booked out goods before, see <a href="http://www.bpm-guide.de/2012/03/02/activiti-5-9-introduces-bpmn-compensation-and-transactions/" class="external-link" rel="nofollow">BPMN Compensation and Transactions Blog Post</a> for details, showing an example as well:</p><p><img class="confluence-embedded-image confluence-external-resource" src="http://www.bpm-guide.de/wp-content/uploads/2012/02/bpmn.transaction.subprocess.example.2.png" data-image-src="http://www.bpm-guide.de/wp-content/uploads/2012/02/bpmn.transaction.subprocess.example.2.png" width="500"></p><h1 id="ErrorHandling-MonitoringandRecoveryStrategies">Monitoring and Recovery Strategies</h1><p>In case an error occurred different recovery strategies can be applied.</p><h2 id="ErrorHandling-Lettheuserretry">Let the user retry</h2><p>As mentioned above, the simplest error handling strategy is to throw the exception to the client, meaning the user has to retry the aciton himself. How he does that is up to the user, normally reloading the page or clicking again.</p><h2 id="ErrorHandling-RetryfailedJobs">Retry failed Jobs</h2><p>If you use Jobs as described above you have to have some monitoring which handles failed jobs, because in this case no user sees an exception. Despite some custom retry strategy (see <a href="/confluence/display/foxUserGuide/Custom+Job+Retry+Strategy">Custom Job Retry Strategy</a>) this normally means to have some tool ready.</p><p>In fox cockpit you can easily find and retry failed jobs, as indicated in the screen shot below. For convenience, failed jobs are typically grouped by exception, allowing to e.g. retry all actions, which got a "service x temporarily not available" exception:<br><br>




<span id="gliffy-container-6160498-8341" class="gliffy-container" data-fullwidth="1033" data-ceoid="6062301" data-filename="failed-jobs-list">

            
<span class="gliffy-chrome " style="display:none;">
    <span class="gliffy-item gliffy-first">
        <img class="gliffy-logo" src="/confluence/download/resources/com.gliffy.integration.confluence:gliffy-macro-key/icons/gliffy-logo-20px.png" title="Gliffy" alt="Gliffy">
         Gliffy     </span>
        <span class="gliffy-item gliffy-start-button">
        <a href="/confluence/plugins/gliffy/launchGliffyHtml5.action?name=failed-jobs-list&amp;ceoid=6062301&amp;key=foxUserGuide&amp;lastPage=%2Fpages%2Fviewpage.action%3FpageId%3D6062301&amp;pageId=6062301&amp;inline=false" target="">
            <span>
                <img src="/confluence/download/resources/com.gliffy.integration.confluence:gliffy-macro-key/icons/gliffy_macro_icon_edit.png" class="gliffy-icon-edit" alt="Edit" title="Edit">
                 Edit             </span>
        </a>
    </span>
            <span class="gliffy-item gliffy-zoom gliffy-end-button ">
        <a href="/confluence/download/attachments/6062301/failed-jobs-list.png?version=1&amp;modificationDate=1340026453000" target="_self">
            <span>
                <img src="/confluence/download/resources/com.gliffy.integration.confluence:gliffy-macro-key/icons/gliffy_macro_icon_zoom.png" class="gliffy-icon-full" alt="Zoom" title="Zoom">
                 Zoom             </span>
        </a>
    </span>
    </span>
    
    <iframe class="gliffy-html5-container" id="gliffy-html5-6160498-8341" src="/confluence/plugins/gliffy/viewer.action" data-id="6160498" data-version="1" data-scale="0.48402712" style="position: relative; overflow: hidden; background: none repeat scroll 0% 0% rgb(255, 255, 255); height: 303px; width: 503px;" frameborder="0" height="301" width="500"></iframe>

        <img class="gliffy-container-icon" src="/confluence/download/resources/com.gliffy.integration.confluence:gliffy-macro-key/icons/gliffy-logo-20px.png" title="Gliffy" alt="Gliffy">

    <span class="gliffy-error-fallback">
        <map id="gliffy-map-6160498-1170" name="gliffy-map-6160498-1170">

        <img id="gliffy-image-6160498-8341" class="gliffy-image " data-full-width="1033" data-full-height="621" src="/confluence/download/attachments/6062301/failed-jobs-list.png?version=1&amp;modificationDate=1340026453000" usemap="#gliffy-map-6160498-1170" height="301" width="500">

        <map id="gliffy-dynamic-map-6160498-8341" class="gliffy-dynamic" name="gliffy-dynamic-map-6160498-8341"></map>
    </map></span>

</span>

<br><br>You can not increase the retries of the failed jobs, meaning&nbsp;<a href="/confluence/display/foxUserGuide/The+Job+Executor">The Job Executor</a> will pick up the jobs and execute them again. This can be done for one process instance, e.g. after correcting some data, or in a batch for all failed instances:</p><p>




<span id="gliffy-container-6160500-8349" class="gliffy-container" data-fullwidth="1601" data-ceoid="6062301" data-filename="correct-data-and-retry">

            
<span class="gliffy-chrome " style="display:none;">
    <span class="gliffy-item gliffy-first">
        <img class="gliffy-logo" src="/confluence/download/resources/com.gliffy.integration.confluence:gliffy-macro-key/icons/gliffy-logo-20px.png" title="Gliffy" alt="Gliffy">
         Gliffy     </span>
        <span class="gliffy-item gliffy-start-button">
        <a href="/confluence/plugins/gliffy/launchGliffyHtml5.action?name=correct-data-and-retry&amp;ceoid=6062301&amp;key=foxUserGuide&amp;lastPage=%2Fpages%2Fviewpage.action%3FpageId%3D6062301&amp;pageId=6062301&amp;inline=false" target="">
            <span>
                <img src="/confluence/download/resources/com.gliffy.integration.confluence:gliffy-macro-key/icons/gliffy_macro_icon_edit.png" class="gliffy-icon-edit" alt="Edit" title="Edit">
                 Edit             </span>
        </a>
    </span>
            <span class="gliffy-item gliffy-zoom gliffy-end-button ">
        <a href="/confluence/download/attachments/6062301/correct-data-and-retry.png?version=1&amp;modificationDate=1340026833000" target="_self">
            <span>
                <img src="/confluence/download/resources/com.gliffy.integration.confluence:gliffy-macro-key/icons/gliffy_macro_icon_zoom.png" class="gliffy-icon-full" alt="Zoom" title="Zoom">
                 Zoom             </span>
        </a>
    </span>
    </span>
    
    <iframe class="gliffy-html5-container" id="gliffy-html5-6160500-8349" src="/confluence/plugins/gliffy/viewer.action" data-id="6160500" data-version="1" data-scale="0.3123048" style="position: relative; overflow: hidden; background: none repeat scroll 0% 0% rgb(255, 255, 255); height: 285px; width: 502px;" frameborder="0" height="283" width="500"></iframe>

        <img class="gliffy-container-icon" src="/confluence/download/resources/com.gliffy.integration.confluence:gliffy-macro-key/icons/gliffy-logo-20px.png" title="Gliffy" alt="Gliffy">

    <span class="gliffy-error-fallback">
        <map id="gliffy-map-6160500-5980" name="gliffy-map-6160500-5980">

        <img id="gliffy-image-6160500-8349" class="gliffy-image " data-full-width="1601" data-full-height="907" src="/confluence/download/attachments/6062301/correct-data-and-retry.png?version=1&amp;modificationDate=1340026833000" usemap="#gliffy-map-6160500-5980" height="283" width="500">

        <map id="gliffy-dynamic-map-6160500-8349" class="gliffy-dynamic" name="gliffy-dynamic-map-6160500-8349"></map>
    </map></span>

</span>

</p><p>That is a rather powerful combination and is recommended to be used in most situations on technical errors. Even if the exception relates to some programming error, you can still fix the problem, redeploy the application and retry the jobs. The process instances will go on in this case.</p><p>If you don't want to use fox cockpit or do not have an enterprise subscription you could find the failed jobs via the API yourself as well. Please note that you cannot do extensive queries available in cockpit here, so e.g. filtering for exceptions, processes or other criteria might involve writing own queries, see <a href="/confluence/display/foxUserGuide/Performance+Tuning+with+custom+Queries">Performance Tuning with custom Queries</a>:</p><div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<div><div id="highlighter_737" class="syntaxhighlighter nogutter  java"><div class="toolbar"><span><a href="#" class="toolbar_item command_help help">?</a></span></div><table border="0" cellpadding="0" cellspacing="0"><tbody><tr><td class="code"><div class="container" title="Hint: double-click to select code"><div class="line number1 index0 alt2"><code class="java plain">List&lt;Job&gt; failedJobs = processEngine.getManagementService().createJobQuery().withException().list();</code></div><div class="line number2 index1 alt1"><code class="java keyword">for</code> <code class="java plain">(Job failedJob : failedJobs) {</code></div><div class="line number3 index2 alt2"><code class="java spaces">&nbsp;&nbsp;</code><code class="java plain">processEngine.getManagementService().setJobRetries(failedJob.getId(), </code><code class="java value">1</code><code class="java plain">);</code></div><div class="line number4 index3 alt1"><code class="java plain">}</code></div></div></td></tr></tbody></table></div></div>
</div></div><h2 id="ErrorHandling-ExplicitModeling">Explicit Modeling</h2><h3 id="ErrorHandling-Retry">Retry</h3><p>Of course you can always model explicitly some retry mechanism as pointed out in <a href="http://www.bpm-guide.de/2012/06/15/where-is-the-retry-in-bpmn-2-0/" class="external-link" rel="nofollow">http://www.bpm-guide.de/2012/06/15/where-is-the-retry-in-bpmn-2-0/</a>:</p><p><img class="confluence-embedded-image confluence-external-resource" src="http://2.bp.blogspot.com/-3ddUw_gnDwI/T9svoUP-0sI/AAAAAAAAABg/MxPGsSoJrZ8/s1600/retry.PNG" data-image-src="http://2.bp.blogspot.com/-3ddUw_gnDwI/T9svoUP-0sI/AAAAAAAAABg/MxPGsSoJrZ8/s1600/retry.PNG" width="500"></p><p>We would recommend to limit it to cases where you either want to see it in the process diagram for a good reason. We prefer asynchronous continuation, since it doesn't bloat your process diagram and basically can do the same thing with even less runtime overhead, since "walking" through the modeled loop involves e.g. writing an audit log.</p><h3 id="ErrorHandling-TasksforOperations">Tasks for Operations</h3><p>We often see something like this in projects:<br><br><img class="confluence-embedded-image" src="/confluence/download/attachments/6062301/error-handling.png?version=1&amp;modificationDate=1340021532000" data-image-src="/confluence/download/attachments/6062301/error-handling.png?version=1&amp;modificationDate=1340021532000" width="750"></p><p>Actually this is a valid approach where you assign errors as User Tasks to some operator and model what possibilities he has to solve the problem. However, this is a strange mixture: We want to handle some technical error but add it to our business process model. Where do we stop? Don't we have to model it on every Service Task now?</p><p>Having a failed jobs list instead of using the "normal" task list feels like a more natural approach for this situation, that's why we normally recommend the other possibility and do <strong>not consider this to be best practice</strong>.</p>